feat: Add concurrent integration tests
awslabs/aws-sdk-swift pull request #1596
Opened 2024-06-27 21:11 UTC by sichanyoo

## Issue \#

https://github.com/awslabs/aws-sdk-swift/issues/1561

## Description of changes

- Adds utility function that concurrently runs a passed-in function `count` times, taken from draft PR: https://github.com/awslabs/aws-sdk-swift/pull/1484
- Add simple concurrent integration tests for STS and S3
- Add integration tests for S3 that put & get 100MB files, and add tests that run them concurrently

## New/existing dependencies impact assessment, if applicable

## Conventional Commits

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-07-02 22:14 UTC, jbelkins requested changes
The rest of this is fine, but let's not commit 100MB of garbage to the project.  Try generating that data in a temp dir, then using that in the test.

2024-07-12 18:20 UTC, jbelkins requested changes
See individual comments

2024-09-18 18:26 UTC, sichanyoo commented on IntegrationTests/Services/AWSS3IntegrationTests/S3ConcurrentTests.swift
> +        var wholeData = Data()
It looks like our `FileStream` type doesn't allow automatic append to the end; I'll just use Swift's library instead.

2024-09-18 18:27 UTC, sichanyoo commented on IntegrationTests/Services/AWSS3IntegrationTests/S3ConcurrentTests.swift
> +        guard let segmentData = stringSegment.data(using: .utf8) else {
Suggestion adopted.

2024-09-19 22:02 UTC, jbelkins reviewed
One question

2024-09-19 22:10 UTC, sichanyoo commented on IntegrationTests/AWSIntegrationTestUtils/ConcurrentTestHelper.swift
> +public func repeatConcurrentlyWithArgs(
I don't think so, because the closure type (function signature of the test function) must have `Any...` instead of being empty.

2024-09-21 01:27 UTC, jbelkins approved these changes
Tests still seem to take quite a while (10 sec per test on Linux+CRT, 30 per sec on Mac+URLSession) but I'm approving because the tests do what they are supposed to do.

If we want to adjust the number of concurrent runs or the test duration, we can do that at a later time.

2024-09-23 15:54 UTC, merged