feat! Full support for file based configurations
awslabs/aws-sdk-swift pull request #935
Opened 2023-03-29 14:32 UTC by epau

## Issue \#

## Description of changes

## New/existing dependencies impact assessment, if applicable

## Conventional Commits

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-03-30 18:43 UTC, epau commented on Sources/Core/AWSClientRuntime/FileBasedConfiguration/Store/FileBasedConfigurationStore.swift
> +    public func fileBasedConfiguration(configFilePath: String?, credentialsFilePath: String?) async throws -> FileBasedConfigurationSectionProviding? {
Update return type to `FileBasedConfiguration`

2023-03-30 18:53 UTC, epau commented on Sources/Core/AWSClientRuntime/Signing/AWSSigningConfig.swift
> +            credentialsProvider: nil, //credentialsProvider?.crtCredentialsProvider,
update this

2023-03-30 18:57 UTC, epau commented on Sources/Core/AWSClientRuntime/Auth/CredentialsProvider/CredentialsProvider.swift
> +/// Direct initailization is not supported.
typo

2023-03-31 16:05 UTC, jbelkins requested changes

2023-03-31 16:38 UTC, epau commented on Sources/Core/AWSClientRuntime/Auth/CredentialsProvider/CredentialsProvider.swift
> +    @_spi(Internal)
That's a good question and something I considered when doing this. I think currently it's unclear how we want to organize this. I'd like to defer that decision to the next time we want use `@_spi()` for a feature. At that time we can play around a bit with this and make a decision that makes most sense.

2023-03-31 19:26 UTC, jbelkins approved these changes

2023-04-03 17:30 UTC, merged